<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Zoe Zhao and (UID 106070449)">

<title>Biostat 203B Homework 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="HW1Solution_files/libs/clipboard/clipboard.min.js"></script>
<script src="HW1Solution_files/libs/quarto-html/quarto.js"></script>
<script src="HW1Solution_files/libs/quarto-html/popper.min.js"></script>
<script src="HW1Solution_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="HW1Solution_files/libs/quarto-html/anchor.min.js"></script>
<link href="HW1Solution_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="HW1Solution_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="HW1Solution_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="HW1Solution_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="HW1Solution_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#q1.-gitgithub" id="toc-q1.-gitgithub" class="nav-link active" data-scroll-target="#q1.-gitgithub"><span class="toc-section-number">1</span>  Q1. Git/GitHub</a></li>
  <li><a href="#q2.-data-ethics-training" id="toc-q2.-data-ethics-training" class="nav-link" data-scroll-target="#q2.-data-ethics-training"><span class="toc-section-number">2</span>  Q2. Data ethics training</a></li>
  <li><a href="#q3.-linux-shell-commands" id="toc-q3.-linux-shell-commands" class="nav-link" data-scroll-target="#q3.-linux-shell-commands"><span class="toc-section-number">3</span>  Q3. Linux Shell Commands</a></li>
  <li><a href="#q4.-whos-popular-in-price-and-prejudice" id="toc-q4.-whos-popular-in-price-and-prejudice" class="nav-link" data-scroll-target="#q4.-whos-popular-in-price-and-prejudice"><span class="toc-section-number">4</span>  Q4. Who’s popular in Price and Prejudice</a></li>
  <li><a href="#q5.-more-fun-with-linux" id="toc-q5.-more-fun-with-linux" class="nav-link" data-scroll-target="#q5.-more-fun-with-linux"><span class="toc-section-number">5</span>  Q5. More fun with Linux</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Biostat 203B Homework 1</h1>
<p class="subtitle lead">Due Jan 27 @ 11:59PM</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Zoe Zhao and (UID 106070449) </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<p>Display machine information for reproducibility:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur ... 10.16

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.2.1  magrittr_2.0.3  fastmap_1.1.0   cli_3.4.1      
 [5] tools_4.2.1     htmltools_0.5.3 rstudioapi_0.14 yaml_2.3.5     
 [9] stringi_1.7.8   rmarkdown_2.16  knitr_1.40      stringr_1.4.1  
[13] xfun_0.33       digest_0.6.29   jsonlite_1.8.0  rlang_1.0.6    
[17] evaluate_0.16  </code></pre>
</div>
</div>
<section id="q1.-gitgithub" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="q1.-gitgithub"><span class="header-section-number">1</span> Q1. Git/GitHub</h2>
<p><strong>No handwritten homework reports are accepted for this course.</strong> We work with Git and GitHub. Efficient and abundant use of Git, e.g., frequent and well-documented commits, is an important criterion for grading your homework.</p>
<ol type="1">
<li>Apply for the <a href="https://education.github.com/pack">Student Developer Pack</a> at GitHub using your UCLA email. You’ll get GitHub Pro account for free (unlimited public and private repositories).</li>
</ol>
<p><strong>Solution:</strong> Done</p>
<ol start="2" type="1">
<li>Create a <strong>private</strong> repository <code>biostat-203b-2023-winter</code> and add <code>Hua-Zhou</code> and <code>tomokiokuno0528</code> as your collaborators with write permission.</li>
</ol>
<p><strong>Solution:</strong> Done</p>
<ol start="3" type="1">
<li>Top directories of the repository should be <code>hw1</code>, <code>hw2</code>, … Maintain two branches <code>master</code> and <code>develop</code>. The <code>develop</code> branch will be your main playground, the place where you develop solution (code) to homework problems and write up report. The <code>master</code> branch will be your presentation area. Submit your homework files (Quarto file <code>qmd</code>, <code>html</code> file converted by Quarto, all code and extra data sets to reproduce results) in <code>main</code> branch.</li>
</ol>
<p><strong>Solution:</strong> Done</p>
<ol start="4" type="1">
<li>After each homework due date, course reader and instructor will check out your <code>master</code> branch for grading. Tag each of your homework submissions with tag names <code>hw1</code>, <code>hw2</code>, … Tagging time will be used as your submission time. That means if you tag your <code>hw1</code> submission after deadline, penalty points will be deducted for late submission.</li>
</ol>
<p><strong>Solution:</strong> Done</p>
<ol start="5" type="1">
<li>After this course, you can make this repository public and use it to demonstrate your skill sets on job market.</li>
</ol>
<p><strong>Solution:</strong> Done</p>
</section>
<section id="q2.-data-ethics-training" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="q2.-data-ethics-training"><span class="header-section-number">2</span> Q2. Data ethics training</h2>
<p>This exercise (and later in this course) uses the <a href="https://mimic-iv.mit.edu">MIMIC-IV data</a>, a freely accessible critical care database developed by the MIT Lab for Computational Physiology. Follow the instructions at <a href="https://mimic.mit.edu/docs/gettingstarted/" class="uri">https://mimic.mit.edu/docs/gettingstarted/</a> to (1) complete the CITI <code>Data or Specimens Only Research</code> course and (2) obtain the PhysioNet credential for using the MIMIC-IV data. Display the verification links to your completion report and completion certificate here. (Hint: The CITI training takes a couple hours and the PhysioNet credentialing takes a couple days; do not leave it to the last minute.)</p>
<p><strong>Link to the completion report : </strong> <a href="https://www.citiprogram.org/verify/?kdcd09fb1-e73c-4d63-8b57-3c29998c7c9b-53914118" class="uri">https://www.citiprogram.org/verify/?kdcd09fb1-e73c-4d63-8b57-3c29998c7c9b-53914118</a></p>
<p><strong>Link to the completion certificate : </strong> <a href="https://www.citiprogram.org/verify/?wfb1ae954-1f90-4467-ae24-19d609bb57b6-53914118" class="uri">https://www.citiprogram.org/verify/?wfb1ae954-1f90-4467-ae24-19d609bb57b6-53914118</a></p>
</section>
<section id="q3.-linux-shell-commands" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="q3.-linux-shell-commands"><span class="header-section-number">3</span> Q3. Linux Shell Commands</h2>
<ol type="1">
<li>The <code>~/mimic</code> folder within the Docker container contains data sets from MIMIC-IV. Refer to the documentation <a href="https://mimic.mit.edu/docs/iv/" class="uri">https://mimic.mit.edu/docs/iv/</a> for details of data files.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ls</span> <span class="at">-l</span> ~/mimic/ </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>total 24
-rw-rw-r--@  1 Aoki  staff  2518 Mar 10  2021 LICENSE.txt
drwxr-xr-x@  5 Aoki  staff   160 Jan 26 10:12 MIMIC-reduce-chartevents
-rw-rw-r--@  1 Aoki  staff  2459 Mar 16  2021 SHA256SUMS.txt
drwxr-xr-x@  6 Aoki  staff   192 Jan 26 10:12 core
drwxr-xr-x@ 21 Aoki  staff   672 Jan 26 10:12 hosp
drwxr-xr-x@ 11 Aoki  staff   352 Jan 26 10:12 icu
-rw-rw-r--@  1 Aoki  staff   797 Jan  4  2022 index.html</code></pre>
</div>
</div>
<p>Please, do <strong>not</strong> put these data files into Git; they are big. Do <strong>not</strong> copy them into your directory. Do <strong>not</strong> decompress the gz data files. These create unnecessary big files on storage and are not big data friendly practices. Just read from the data folder <code>~/mimic</code> directly in following exercises.</p>
<p>Use Bash commands to answer following questions.</p>
<p><strong>Solution: </strong> Done</p>
<ol start="2" type="1">
<li>Display the contents in the folders <code>core</code>, <code>hosp</code>, <code>icu</code>. Why are these data files distributed as <code>.csv.gz</code> files instead of <code>.csv</code> (comma separated values) files? Read the page <a href="https://mimic.mit.edu/docs/iv/" class="uri">https://mimic.mit.edu/docs/iv/</a> to understand what’s in each folder.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ls</span> <span class="at">-l</span> ~/mimic/core</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>total 142944
-rw-rw-r--@ 1 Aoki  staff  17208966 Mar 15  2021 admissions.csv.gz
-rw-rw-r--@ 1 Aoki  staff       606 Jan  4  2022 index.html
-rw-rw-r--@ 1 Aoki  staff   2955582 Mar 15  2021 patients.csv.gz
-rw-rw-r--@ 1 Aoki  staff  53014503 Mar 15  2021 transfers.csv.gz</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ls</span> <span class="at">-l</span> ~/mimic/hosp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>total 9243184
-rw-rw-r--@ 1 Aoki  staff      430049 Mar 15  2021 d_hcpcs.csv.gz
-rw-rw-r--@ 1 Aoki  staff      863239 Mar 15  2021 d_icd_diagnoses.csv.gz
-rw-rw-r--@ 1 Aoki  staff      579998 Mar 15  2021 d_icd_procedures.csv.gz
-rw-rw-r--@ 1 Aoki  staff       14898 Mar 15  2021 d_labitems.csv.gz
-rw-rw-r--@ 1 Aoki  staff    29531152 Mar 15  2021 diagnoses_icd.csv.gz
-rw-rw-r--@ 1 Aoki  staff    11684062 Mar 15  2021 drgcodes.csv.gz
-rw-rw-r--@ 1 Aoki  staff   515763427 Mar 15  2021 emar.csv.gz
-rw-rw-r--@ 1 Aoki  staff   476252563 Mar 15  2021 emar_detail.csv.gz
-rw-rw-r--@ 1 Aoki  staff     2098831 Mar 15  2021 hcpcsevents.csv.gz
-rw-rw-r--@ 1 Aoki  staff        2325 Jan  4  2022 index.html
-rw-rw-r--@ 1 Aoki  staff  2091865786 Mar 15  2021 labevents.csv.gz
-rw-rw-r--@ 1 Aoki  staff   171624288 Jan 27  2022 labevents_filtered_itemid.csv.gz
-rw-rw-r--@ 1 Aoki  staff    99133381 Mar 15  2021 microbiologyevents.csv.gz
-rw-rw-r--@ 1 Aoki  staff   422874088 Mar 15  2021 pharmacy.csv.gz
-rw-rw-r--@ 1 Aoki  staff   501381155 Mar 15  2021 poe.csv.gz
-rw-rw-r--@ 1 Aoki  staff    24020923 Mar 15  2021 poe_detail.csv.gz
-rw-rw-r--@ 1 Aoki  staff   367041717 Mar 15  2021 prescriptions.csv.gz
-rw-rw-r--@ 1 Aoki  staff     7750325 Mar 15  2021 procedures_icd.csv.gz
-rw-rw-r--@ 1 Aoki  staff     9565293 Mar 15  2021 services.csv.gz</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ls</span> <span class="at">-l</span> ~/mimic/icu</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>total 5698008
-rw-rw-r--@ 1 Aoki  staff  2350783547 Mar 15  2021 chartevents.csv.gz
-rw-rw-r--@ 1 Aoki  staff   110272408 Jan 27  2022 chartevents_filtered_itemid.csv.gz
-rw-rw-r--@ 1 Aoki  staff       55917 Mar 15  2021 d_items.csv.gz
-rw-rw-r--@ 1 Aoki  staff    43296273 Mar 15  2021 datetimeevents.csv.gz
-rw-rw-r--@ 1 Aoki  staff     2848628 Mar 15  2021 icustays.csv.gz
-rw-rw-r--@ 1 Aoki  staff        1103 Jan  4  2022 index.html
-rw-rw-r--@ 1 Aoki  staff   352443512 Mar 15  2021 inputevents.csv.gz
-rw-rw-r--@ 1 Aoki  staff    37095672 Mar 15  2021 outputevents.csv.gz
-rw-rw-r--@ 1 Aoki  staff    20567368 Mar 15  2021 procedureevents.csv.gz</code></pre>
</div>
</div>
<p><strong>Solution:</strong> The “csv.gz” files are a compressed form of the cvs file. The CSV.GZ is a CSV file compressed with gzip utility. Unzip the compressed file will generate the csv files. The CSV file is the file in which information is separated by commas.</p>
<ol start="3" type="1">
<li>Briefly describe what bash commands <code>zcat</code>, <code>zless</code>, <code>zmore</code>, and <code>zgrep</code> do.</li>
</ol>
<p><strong>Solution:</strong> These are the command used on the compressed file. (zcat, zless, zmore, and zgrep) equals (cat, less, more, and grep)</p>
<p>‘zcat’ uncompresses either a list of files on the command line or its standard input and writes the uncompressed data on standard output.</p>
<p>‘zless’ and zmore are filters which allows examination of compressed or plain text files one screenful at a time on a soft-copy terminal. (The less is more powerful than more.)</p>
<p>‘zgrep’ command is used to search out expressions from a given a file even if it is compressed.</p>
<ol start="4" type="1">
<li>What’s the output of the following bash script?</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> datafile <span class="kw">in</span> ~/mimic/core/<span class="pp">*</span>.gz</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="cf">do</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ls</span> <span class="at">-l</span> <span class="va">$datafile</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="cf">done</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>-rw-rw-r--@ 1 Aoki  staff  17208966 Mar 15  2021 /Users/Aoki/mimic/core/admissions.csv.gz
-rw-rw-r--@ 1 Aoki  staff  2955582 Mar 15  2021 /Users/Aoki/mimic/core/patients.csv.gz
-rw-rw-r--@ 1 Aoki  staff  53014503 Mar 15  2021 /Users/Aoki/mimic/core/transfers.csv.gz</code></pre>
</div>
</div>
<p><strong>Solution</strong> It finds out all the datafiles in the folder “~/mimic/core/” that ends with a name of “gz” and print the names and information of them out one by one, as a long format with it “ls” information results.</p>
<p>Display the number of lines in each data file using a similar loop.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> datafile <span class="kw">in</span> ~/mimic/core/<span class="pp">*</span>gz</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="cf">do</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ls</span> <span class="va">$datafile</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="ex">gzcat</span> <span class="va">$datafile</span> <span class="kw">|</span> <span class="fu">wc</span> <span class="at">-l</span> </span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="cf">done</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>/Users/Aoki/mimic/core/admissions.csv.gz
  523741
/Users/Aoki/mimic/core/patients.csv.gz
  382279
/Users/Aoki/mimic/core/transfers.csv.gz
 2189536</code></pre>
</div>
</div>
<p><strong>Solution: </strong> : 523741 in admissions.csv.gz, 382279 in patients.csv.gz, 2189536, transfers.csv.gz.</p>
<ol start="5" type="1">
<li>Display the first few lines of <code>admissions.csv.gz</code>. How many rows are in this data file? How many unique patients (identified by <code>subject_id</code>) are in this data file? (Hint: combine Linux commands <code>zcat</code>, <code>head</code>/<code>tail</code>, <code>awk</code>, <code>sort</code>, <code>uniq</code>, <code>wc</code>, and so on.)</li>
</ol>
<p><strong>Display the first few lines of <code>admissions.csv.gz</code>.</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="ex">gzcat</span> ~/mimic/core/admissions.csv.gz <span class="kw">|</span> <span class="fu">head</span> <span class="at">-10</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admission_location,discharge_location,insurance,language,marital_status,ethnicity,edregtime,edouttime,hospital_expire_flag
14679932,21038362,2139-09-26 14:16:00,2139-09-28 11:30:00,,ELECTIVE,,HOME,Other,ENGLISH,SINGLE,UNKNOWN,,,0
15585972,24941086,2123-10-07 23:56:00,2123-10-12 11:22:00,,ELECTIVE,,HOME,Other,ENGLISH,,WHITE,,,0
11989120,21965160,2147-01-14 09:00:00,2147-01-17 14:25:00,,ELECTIVE,,HOME,Other,ENGLISH,,UNKNOWN,,,0
17817079,24709883,2165-12-27 17:33:00,2165-12-31 21:18:00,,ELECTIVE,,HOME,Other,ENGLISH,,OTHER,,,0
15078341,23272159,2122-08-28 08:48:00,2122-08-30 12:32:00,,ELECTIVE,,HOME,Other,ENGLISH,,BLACK/AFRICAN AMERICAN,,,0
19124609,20517215,2169-03-14 12:44:00,2169-03-20 19:15:00,,ELECTIVE,,HOME,Other,ENGLISH,,UNKNOWN,,,0
17301855,29732723,2140-06-06 14:23:00,2140-06-08 14:25:00,,ELECTIVE,,HOME,Other,ENGLISH,,WHITE,,,0
17991012,24298836,2181-07-10 20:28:00,2181-07-12 15:49:00,,ELECTIVE,,HOME,Other,ENGLISH,,WHITE,,,0
16865435,23216961,2185-07-19 02:12:00,2185-07-21 11:50:00,,ELECTIVE,,HOME,Other,ENGLISH,,WHITE,,,0</code></pre>
</div>
</div>
<p><strong>Solution: </strong> The first 10 rows displayed by the command above</p>
<p><strong>How many rows are in this data file?</strong></p>
<p><strong>-Show the first lines of the data</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="ex">gzcat</span> ~/mimic/core/admissions.csv.gz <span class="kw">|</span> <span class="fu">head</span> <span class="at">-3</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admission_location,discharge_location,insurance,language,marital_status,ethnicity,edregtime,edouttime,hospital_expire_flag
14679932,21038362,2139-09-26 14:16:00,2139-09-28 11:30:00,,ELECTIVE,,HOME,Other,ENGLISH,SINGLE,UNKNOWN,,,0
15585972,24941086,2123-10-07 23:56:00,2123-10-12 11:22:00,,ELECTIVE,,HOME,Other,ENGLISH,,WHITE,,,0</code></pre>
</div>
</div>
<p><strong>-Show the last lines of the data</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="ex">gzcat</span> ~/mimic/core/admissions.csv.gz <span class="kw">|</span> <span class="fu">tail</span> <span class="at">-3</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>19389857,23176714,2189-03-01 00:58:00,2189-03-02 15:22:00,,SURGICAL SAME DAY ADMISSION,PHYSICIAN REFERRAL,HOME,Other,ENGLISH,MARRIED,WHITE,,,0
12298845,22347500,2138-05-31 00:00:00,2138-06-04 16:50:00,,SURGICAL SAME DAY ADMISSION,PHYSICIAN REFERRAL,HOME HEALTH CARE,Other,ENGLISH,MARRIED,WHITE,,,0
11211939,24981356,2147-08-02 15:49:00,2147-08-05 16:30:00,,EW EMER.,EMERGENCY ROOM,HOME HEALTH CARE,Medicare,?,WIDOWED,WHITE,2147-08-02 14:27:00,2147-08-02 17:38:00,0</code></pre>
</div>
</div>
<p><strong>Findings: </strong> Based on the result we know that the first line is the name of the variables and start from the second line, each line is a patient.<br>
We use the awk command to ignore the first row and use the we -l to count the number of the lines which could represent the number of the rows.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="ex">gzcat</span> ~/mimic/core/admissions.csv.gz <span class="kw">|</span> <span class="fu">awk</span>  <span class="st">'  NR &gt; 1  '</span> <span class="kw">|</span> <span class="fu">wc</span> <span class="at">-l</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  523740</code></pre>
</div>
</div>
<p><strong>Solution:</strong> There are 523740 rows in this file</p>
<p><strong>How many unique patients (identified by <code>subject_id</code>) are in this data file?</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="ex">gzcat</span> ~/mimic/core/admissions.csv.gz <span class="kw">|</span> <span class="dt">\</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">awk</span> <span class="at">-F</span> , <span class="st">' NR &gt; 1 { print $1 } '</span> <span class="kw">|</span> <span class="fu">sort</span> <span class="at">-u</span> <span class="kw">|</span> <span class="fu">uniq</span> <span class="at">-c</span> <span class="kw">|</span> <span class="fu">wc</span> <span class="at">-l</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  256878</code></pre>
</div>
</div>
<p><strong>Solution: </strong> There are 256878 unique patients in this file</p>
<ol start="6" type="1">
<li>What are the possible values taken by each of the variable <code>admission_type</code>, <code>admission_location</code>, <code>insurance</code>, and <code>ethnicity</code>? Also report the count for each unique value of these variables. (Hint: combine Linux commands <code>zcat</code>, <code>head</code>/<code>tail</code>, <code>awk</code>, <code>uniq -c</code>, <code>wc</code>, and so on.)</li>
</ol>
<p><strong>6.1: admission-type</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="ex">gzcat</span> ~/mimic/core/admissions.csv.gz <span class="kw">|</span> <span class="dt">\</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">awk</span> <span class="at">-F</span> , <span class="st">' NR &gt; 1 { print $6 } '</span> <span class="kw">|</span> <span class="fu">sort</span> <span class="kw">|</span> <span class="fu">uniq</span> <span class="at">-c</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>7254 AMBULATORY OBSERVATION
21581 DIRECT EMER.
19991 DIRECT OBSERVATION
72072 ELECTIVE
100445 EU OBSERVATION
157896 EW EMER.
55497 OBSERVATION ADMIT
41074 SURGICAL SAME DAY ADMISSION
47930 URGENT</code></pre>
</div>
</div>
<p><strong>6.2: admission_location</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="ex">gzcat</span> ~/mimic/core/admissions.csv.gz <span class="kw">|</span> <span class="dt">\</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">awk</span> <span class="at">-F</span> , <span class="st">' NR &gt; 1 { print $7 } '</span> <span class="kw">|</span> <span class="fu">sort</span> <span class="kw">|</span> <span class="fu">uniq</span> <span class="at">-c</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>60435 
 191 AMBULATORY SURGERY TRANSFER
10670 CLINIC REFERRAL
245744 EMERGENCY ROOM
 379 INFORMATION NOT AVAILABLE
4467 INTERNAL TRANSFER TO OR FROM PSYCH
6067 PACU
127494 PHYSICIAN REFERRAL
8449 PROCEDURE SITE
39121 TRANSFER FROM HOSPITAL
4063 TRANSFER FROM SKILLED NURSING FACILITY
16660 WALK-IN/SELF REFERRAL</code></pre>
</div>
</div>
<p><strong>6.3 insurance</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="ex">gzcat</span> ~/mimic/core/admissions.csv.gz <span class="kw">|</span> <span class="dt">\</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">awk</span> <span class="at">-F</span> , <span class="st">' NR &gt; 1 { print $9 } '</span> <span class="kw">|</span> <span class="fu">sort</span> <span class="kw">|</span> <span class="fu">uniq</span> <span class="at">-c</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>50850 Medicaid
171360 Medicare
301530 Other</code></pre>
</div>
</div>
<p><strong>6.4 ethnicity</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="ex">gzcat</span> ~/mimic/core/admissions.csv.gz <span class="kw">|</span> <span class="dt">\</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">awk</span> <span class="at">-F</span> , <span class="st">' NR &gt; 1 { print $12 } '</span> <span class="kw">|</span> <span class="fu">sort</span> <span class="kw">|</span> <span class="fu">uniq</span> <span class="at">-c</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1535 AMERICAN INDIAN/ALASKA NATIVE
24506 ASIAN
80293 BLACK/AFRICAN AMERICAN
29823 HISPANIC/LATINO
26813 OTHER
3740 UNABLE TO OBTAIN
19400 UNKNOWN
337630 WHITE</code></pre>
</div>
</div>
</section>
<section id="q4.-whos-popular-in-price-and-prejudice" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="q4.-whos-popular-in-price-and-prejudice"><span class="header-section-number">4</span> Q4. Who’s popular in Price and Prejudice</h2>
<ol type="1">
<li>You and your friend just have finished reading <em>Pride and Prejudice</em> by Jane Austen. Among the four main characters in the book, Elizabeth, Jane, Lydia, and Darcy, your friend thinks that Darcy was the most mentioned. You, however, are certain it was Elizabeth. Obtain the full text of the novel from <a href="http://www.gutenberg.org/cache/epub/42671/pg42671.txt" class="uri">http://www.gutenberg.org/cache/epub/42671/pg42671.txt</a> and save to your local folder.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="ex">curl</span> <span class="at">-L</span> <span class="at">-O</span>  http://www.gutenberg.org/cache/epub/42671/pg42671.txt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

 95  708k   95  677k    0     0   571k      0  0:00:01  0:00:01 --:--:--  571k
100  708k  100  708k    0     0   597k      0  0:00:01  0:00:01 --:--:-- 29.9M</code></pre>
</div>
</div>
<p><strong>Solution: </strong> Done</p>
<p>Explain what <code>wget -nc</code> does. Do <strong>not</strong> put this text file <code>pg42671.txt</code> in Git. Complete the following loop to tabulate the number of times each of the four characters is mentioned using Linux commands.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="ex">curl</span> <span class="at">-L</span> <span class="at">-O</span>  http://www.gutenberg.org/cache/epub/42671/pg42671.txt</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> char <span class="kw">in</span> Elizabeth Jane Lydia Darcy</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="cf">do</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="bu">echo</span> <span class="va">$char</span>:</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># match word ignoring cases</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span> pg42671.txt <span class="kw">|</span> <span class="fu">grep</span> <span class="at">-o</span> <span class="at">-i</span> <span class="va">$char</span> <span class="kw">|</span> <span class="fu">wc</span> <span class="at">-l</span> </span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="cf">done</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

 12  708k   12 91756    0     0  92354      0  0:00:07 --:--:--  0:00:07 92354
100  708k  100  708k    0     0   543k      0  0:00:01  0:00:01 --:--:-- 2007k
Elizabeth:
     634
Jane:
     294
Lydia:
     171
Darcy:
     418</code></pre>
</div>
</div>
<p><strong>Explain what wget -nc does.</strong> <strong>Solution:</strong> I am not using the wget to finish this quesiton. But based on the curl which have a similar function with it. It is a command that downloads source code and binaries, and retrieve an entire website or a specific hierarchy at once. <strong>Solution:</strong> Elizabeth is mentioned 634 times. Jane 294 times. Lydia 171 times. Darcy 418 times.</p>
<ol start="2" type="1">
<li>What’s the difference between the following two commands?</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="bu">echo</span> <span class="st">'hello, world'</span> <span class="op">&gt;</span> test1.txt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>and</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="bu">echo</span> <span class="st">'hello, world'</span> <span class="op">&gt;&gt;</span> test2.txt </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Solution</strong> The first command use only one “&gt;”. It put the string ‘hello, world’ into a txt file called: test1.txt. The second command have two “&gt;” and are used to append the string we want at the end of the original file. For the first file, no matter how much time you runit. You will get only one ‘hello, world’ in the txt file. For the second file, the more time you run, the more ‘hello, world’ lines are appended to the file test2.txt.</p>
<ol start="3" type="1">
<li>Using your favorite text editor (e.g., <code>vi</code>), type the following and save the file as <code>middle.sh</code>:</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co">#!/bin/sh</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Select lines from the middle of a file.</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Usage: bash middle.sh filename end_line num_lines</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span> <span class="at">-n</span> <span class="st">"</span><span class="va">$2</span><span class="st">"</span> <span class="st">"</span><span class="va">$1</span><span class="st">"</span> <span class="kw">|</span> <span class="fu">tail</span> <span class="at">-n</span> <span class="st">"</span><span class="va">$3</span><span class="st">"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Solution</strong>: Done</p>
<p>Using <code>chmod</code> to make the file executable by the owner, and run</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chmod</span> 700 ./middle.sh</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="ex">./middle.sh</span> pg42671.txt 20 5</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Author: Jane Austen

Editor: R. W. (Robert William) Chapman
</code></pre>
</div>
</div>
<p>Explain the output. Explain the meaning of <code>"$1"</code>, <code>"$2"</code>, and <code>"$3"</code> in this shell script. Why do we need the first line of the shell script?</p>
<p><strong>Explain the output.</strong></p>
<p><strong>Solution :</strong> The out put means the last 5 rows of the first 20 rows (15-20 rows) of the pg42671.txt file. In the string: “pg42671.txt 20 5”, $1 is the pg42671.txt. $2 is 20, and $3 is 5.</p>
<p><strong>Why do we need the first line of the shell script?</strong></p>
<p><strong>Solution :</strong> The first line is used to identify the shell to execute.</p>
</section>
<section id="q5.-more-fun-with-linux" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="q5.-more-fun-with-linux"><span class="header-section-number">5</span> Q5. More fun with Linux</h2>
<p>Try following commands in Bash and interpret the results: <code>cal</code>, <code>cal 2021</code>, <code>cal 9 1752</code> (anything unusual?), <code>date</code>, <code>hostname</code>, <code>arch</code>, <code>uname -a</code>, <code>uptime</code>, <code>who am i</code>, <code>who</code>, <code>w</code>, <code>id</code>, <code>last | head</code>, <code>echo {con,pre}{sent,fer}{s,ed}</code>, <code>time sleep 5</code>, <code>history | tail</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cal</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    January 2023      
Su Mo Tu We Th Fr Sa  
 1  2  3  4  5  6  7  
 8  9 10 11 12 13 14  
15 16 17 18 19 20 21  
22 23 24 25 26 _2_7 28  
29 30 31              
                      </code></pre>
</div>
</div>
<p><strong>Solution: </strong> cal can see the calendar of a specific month or a whole year. The null of the cal cammand, will shows the month now. I think it is based on the systen time when the command is run.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cal</span> 2021</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            2021
      January               February               March          
Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  
                1  2      1  2  3  4  5  6      1  2  3  4  5  6  
 3  4  5  6  7  8  9   7  8  9 10 11 12 13   7  8  9 10 11 12 13  
10 11 12 13 14 15 16  14 15 16 17 18 19 20  14 15 16 17 18 19 20  
17 18 19 20 21 22 23  21 22 23 24 25 26 27  21 22 23 24 25 26 27  
24 25 26 27 28 29 30  28                    28 29 30 31           
31                                                                

       April                  May                   June          
Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  
             1  2  3                     1         1  2  3  4  5  
 4  5  6  7  8  9 10   2  3  4  5  6  7  8   6  7  8  9 10 11 12  
11 12 13 14 15 16 17   9 10 11 12 13 14 15  13 14 15 16 17 18 19  
18 19 20 21 22 23 24  16 17 18 19 20 21 22  20 21 22 23 24 25 26  
25 26 27 28 29 30     23 24 25 26 27 28 29  27 28 29 30           
                      30 31                                       

        July                 August              September        
Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  
             1  2  3   1  2  3  4  5  6  7            1  2  3  4  
 4  5  6  7  8  9 10   8  9 10 11 12 13 14   5  6  7  8  9 10 11  
11 12 13 14 15 16 17  15 16 17 18 19 20 21  12 13 14 15 16 17 18  
18 19 20 21 22 23 24  22 23 24 25 26 27 28  19 20 21 22 23 24 25  
25 26 27 28 29 30 31  29 30 31              26 27 28 29 30        
                                                                  

      October               November              December        
Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  
                1  2      1  2  3  4  5  6            1  2  3  4  
 3  4  5  6  7  8  9   7  8  9 10 11 12 13   5  6  7  8  9 10 11  
10 11 12 13 14 15 16  14 15 16 17 18 19 20  12 13 14 15 16 17 18  
17 18 19 20 21 22 23  21 22 23 24 25 26 27  19 20 21 22 23 24 25  
24 25 26 27 28 29 30  28 29 30              26 27 28 29 30 31     
31                                                                </code></pre>
</div>
</div>
<p><strong>Solution</strong> This command: cal + year will show the whole calendar of all months in this specfic year.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cal</span> 9 1752</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   September 1752     
Su Mo Tu We Th Fr Sa  
       1  2 14 15 16  
17 18 19 20 21 22 23  
24 25 26 27 28 29 30  
                      
                      
                      </code></pre>
</div>
</div>
<p><strong>Solution</strong> The cal command, is in the cal [ [ month ] year] syntax. There are some missing dates. The reason is that the calendar switched from the Julian calendar to the Gregorian calendar, so we miss some dates during ths process.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">date</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Fri Jan 27 17:18:16 PST 2023</code></pre>
</div>
</div>
<p><strong>Solution: </strong> The date command, will shows the system time . The result including the abbreviated day name, abbreviated month name, day of the month, the time separated by colons, the time zone name, and the year.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hostname</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>wifi-131-179-47-162.host.ucla.edu</code></pre>
</div>
</div>
<p><strong>Solution: </strong> The hostname command in Linux displays the hostname of the server.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">arch</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>i386</code></pre>
</div>
</div>
<p><strong>Solution: </strong> The arch command displays the architecture of the Linux machine.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">uname</span> <span class="at">-a</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Darwin wifi-131-179-47-162.host.ucla.edu 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64</code></pre>
</div>
</div>
<p><strong>Solution</strong> The uname -a command displays all information on your system such as machine, hostname, and architecture name</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">uptime</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>17:18  up 27 days, 23:16, 3 users, load averages: 8.92 6.41 5.47</code></pre>
</div>
</div>
<p><strong>Solution</strong> The uptime is a command that returns information about how long your system has been running together with the current time, number of users with running sessions, and the system load averages for the past 1, 5, and 15 minutes.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">who</span> am i</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Aoki     tty??    Jan 27 17:18 </code></pre>
</div>
</div>
<p><strong>Solution: </strong>The who am i command display the username of the current user when this command is invoked.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">who</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Aoki      console  Jan 23 16:39 
zhaoyijin console  Jan 10 16:58 
Aoki      ttys002  Jan 27 16:32 </code></pre>
</div>
</div>
<p><strong>Solution:</strong> The who command is a tool print information about users who are currently logged in</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">w</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>17:18  up 27 days, 23:16, 3 users, load averages: 8.92 6.41 5.47
USER     TTY      FROM              LOGIN@  IDLE WHAT
zhaoyijin console  -                10Jan23 17days -
Aoki     console  -                Mon16   4days -
Aoki     s002     -                16:32      45 -bash         &lt;ff&gt;&lt;bf&gt;    /bin/bash </code></pre>
</div>
</div>
<p><strong>Solution:</strong>The w command is a built-in tool that allows administrators to view information about users that are currently logged in.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">id</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>uid=502(Aoki) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),701(com.apple.sharepoint.group.1),702(com.apple.sharepoint.group.2),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),400(com.apple.access_remote_ae)</code></pre>
</div>
</div>
<p><strong>Solution:</strong>Linux id command is used to print the genuine and effective user ID and group ID.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">last</span> <span class="kw">|</span> <span class="fu">head</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Aoki      ttys002                   Fri Jan 27 16:32   still logged in
Aoki      ttys002                   Thu Jan 26 17:48 - 17:48  (00:00)
Aoki      ttys000                   Thu Jan 26 13:00 - 13:00  (00:00)
Aoki      ttys000                   Thu Jan 26 10:14 - 10:14  (00:00)
Aoki      ttys000                   Wed Jan 25 00:09 - 00:09  (00:00)
Aoki      ttys000                   Tue Jan 24 14:59 - 14:59  (00:00)
Aoki      ttys000                   Tue Jan 24 13:19 - 13:19  (00:00)
Aoki      ttys000                   Tue Jan 24 13:14 - 13:14  (00:00)
Aoki      console                   Mon Jan 23 16:39   still logged in
Aoki      ttys000                   Thu Jan 19 13:07 - 13:07  (00:00)</code></pre>
</div>
</div>
<p><strong>Solution:</strong> The last | head command displays the first 10 lines of the list of all the users logged in.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="bu">echo</span> <span class="dt">{con</span><span class="op">,</span><span class="dt">pre}{sent</span><span class="op">,</span><span class="dt">fer}{s</span><span class="op">,</span><span class="dt">ed}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>consents consented confers confered presents presented prefers prefered</code></pre>
</div>
</div>
<p><strong>Solution:</strong> It displays the concatenate 3 fields into 8 different words with different conbinations.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="bu">time</span> sleep 5</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
real    0m5.013s
user    0m0.001s
sys 0m0.007s</code></pre>
</div>
</div>
<p><strong>Solution:</strong> Linux sleep command lets the terminal wait by the specified amount of time. By default, it takes time in seconds. But, we can set the delay time in minutes (m), hours (h), and days (d). It helps in pausing the execution of any particular command for a fixed amount of time.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="bu">history</span> <span class="kw">|</span> <span class="fu">tail</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Solution:</strong> The result is only work in the terminal. These are the results from my terminal.</p>
<p>311 nano 312 ls 313 cat middle.sh 314 man head 315 ls -al 316 chmod 700 #!/bin/sh 317 chmod 700 middle.sh 318 ls -al 319 history | tal 320 history | tail wifi-131-179-47-162:~ Aoki$</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>